import { Box, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>NairaBoom-Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Text>Hello</Text>
    </Box>
  );
}
