import {
  Box,
  Text,
  Avatar,
  Link,
  Input,
  Button,
  chakra,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import notificationbell from "../public/dashboard/notification.svg";
import avatar from "../public/dashboard/avatar.svg";
import searchIcon from "../public/dashboard/search.png";
import transaction from "../public/dashboard/transactions.svg";
import amount from "../public/dashboard/amount.svg";
import nairasign from "../public/dashboard/Nairasign.svg";
import Wrapper from "../components/Wrapper";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>NairaBoom-Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Wrapper>
        <Box
          display={"flex"}
          justifyContent="space-between"
          alignItems={"center"}
          pb="2.25rem"
        >
          <Text fontWeight={700} fontSize="1.5rem" color="nairablue">
            Dashboard
          </Text>
          <Box display={"flex"} alignItems="center" gap="1.6rem">
            <Box as={Link} cursor="pointer">
              <Image src={notificationbell} alt="notification bell" />
            </Box>
            <Avatar
              name="Muhammed Cynthia"
              src={avatar.src}
              bg="rgba(30, 215, 96, 0.19)"
            />
          </Box>
        </Box>
        <form action="">
          <Box
            display={"flex"}
            w={"16.7rem"}
            maxW="90%"
            h="2.5rem"
            borderRadius={"5px"}
            bgColor={"white"}
          >
            <Input
              type="text"
              placeholder="Search"
              h="100%"
              focusBorderColor="none"
              border={"none"}
              _placeholder={{ color: "#A7A7A7" }}
            />
            <Button
              float={"right"}
              type="submit"
              bgColor={"nairagreen"}
              w="3rem"
              h="inherit"
              _hover={{}}
            >
              <Image src={searchIcon} alt="search icon" />
            </Button>
          </Box>
        </form>
        <Box
          pt="2.2rem"
          pb={{ base: "2rem", md: "3.8rem" }}
          display={"flex"}
          flexDir={{ base: "column", md: "row" }}
          alignItems="center"
          justifyContent={"space-between"}
          gap={{ base: "1rem", md: "0rem" }}
        >
          <Box
            bgColor={"white"}
            borderRadius="xl"
            display={"flex"}
            alignItems="center"
            pl="1.25rem"
            gap={{ base: "1rem", md: "1.25rem" }}
            w={{ base: "100%", md: "47%" }}
            py={{ base: "1.5rem", md: "2.5rem" }}
          >
            <Box>
              <Image src={transaction} alt="total transactions" />
            </Box>
            <Box display={"flex"} flexDir="column">
              <Text
                fontSize={{ base: "1rem", md: "xl" }}
                fontWeight={500}
                color={"nairagrey"}
              >
                Total Transactions
              </Text>
              <Text
                color="nairablue"
                fontWeight={700}
                fontSize={{ base: "2rem", md: "2.75rem" }}
              >
                17
              </Text>
            </Box>
          </Box>
          <Box
            bgColor={"white"}
            borderRadius="20px"
            display={"flex"}
            alignItems="center"
            pl="1.2rem"
            gap={{ base: "1rem", md: "1.25rem" }}
            w={{ base: "100%", md: "47%" }}
            py={{ base: "1.5rem", md: "2.5rem" }}
          >
            <Box>
              <Image src={amount} alt="total transactions" />
            </Box>
            <Box display={"flex"} flexDir="column">
              <Text
                fontSize={{ base: "1rem", md: "xl" }}
                fontWeight={500}
                color={"nairagrey"}
              >
                Total Amount Paid
              </Text>
              <Text
                color="nairablue"
                fontWeight={700}
                fontSize={{ base: "2rem", md: "2.75rem" }}
              >
                &#8358;5900
              </Text>
            </Box>
          </Box>
        </Box>
        <Box display={"flex"} w="90%" flexDir="column">
          <Text
            color="nairablue"
            fontWeight={700}
            fontSize={{ base: "1.25rem", md: "1.5rem" }}
          >
            Cashback Payment History
          </Text>
          <Box
            pt={{ base: "2rem", md: "2.75rem" }}
            display={"flex"}
            justifyContent="space-between"
          >
            <Text
              color="nairagrey"
              fontWeight={500}
              fontSize={{ base: ".9rem", md: "1.25rem" }}
            >
              S/N
            </Text>
            <Text
              color="nairagrey"
              fontWeight={500}
              fontSize={{ base: ".9rem", md: "1.25rem" }}
            >
              Timestamp
            </Text>
            <Text
              color="nairagrey"
              fontWeight={500}
              fontSize={{ base: ".9rem", md: "1.25rem" }}
            >
              Timestamp Date
            </Text>
          </Box>
          <Box
            pt={{ base: "1.5rem", md: "2.4rem" }}
            display={"flex"}
            flexDir="column"
            gap="2rem"
          >
            <Box
              display={"flex"}
              justifyContent="space-between"
              pl={{ base: "0rem", md: "1.5rem" }}
              pr={{ base: "0rem", md: "1.5rem" }}
            >
              <Text
                fontSize={{ base: "1rem", md: "lg" }}
                color="nairablue"
                fontWeight={400}
                textAlign="center"
              >
                1
              </Text>
              <Text
                w="7rem"
                fontSize={{ base: "1rem", md: "lg" }}
                color="nairablue"
                fontWeight={400}
                textAlign="center"
              >
                14:20:34
              </Text>
              <Text
                fontSize={{ base: "1rem", md: "lg" }}
                color="nairablue"
                fontWeight={400}
                textAlign="center"
              >
                24, Apr 2021
              </Text>
            </Box>
          </Box>
        </Box>
      </Wrapper>
    </Box>
  );
}
