import { Box, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>NairaBoom-Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box
        bgColor={"#F5F5F5"}
        borderRadius="2rem"
        mt="2rem"
        mb="4.8rem"
        pl="3.8rem"
        pt="2.5rem"
        float="right"
        width={"calc(100% - 25rem)"}
      >
        <Text>Dashboard</Text>
      </Box>
    </Box>
  );
}
